<?xml version="1.0" encoding="utf-8"?><Database Name="DO" Class="DODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-IF2VHJQ\ATECH;Initial Catalog=DO;Integrated Security=True" SettingsObjectName="DeliveryOrder.Properties.Settings" SettingsPropertyName="DOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CarDriver" Member="CarDrivers">
    <Type Name="CarDriver">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="drivingLicenceNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="expiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Working" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Desc]" Member="Desc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Coperator" Member="Coperators">
    <Type Name="Coperator">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CopID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CopDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ComLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComContact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MotoDriver" Member="MotoDrivers">
    <Type Name="MotoDriver">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="drivingLicenceNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="expiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Working" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalerID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CheckInDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToLocation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CusPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CusAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TakeBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TakeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CloseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(16,4)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StopWork" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>